import React from 'react';
import style from './index.module.scss';
import { Button, Image, Text } from '@mantine/core';
import ImageOne from '@/shared/images/image-eco.png';
import ImageTwo from '@/shared/images/image-monitoring.png';
import ImageThree from '@/shared/images/image-emission.png';
import ImageFour from '@/shared/images/image-ambient.png';

export const Ecology = () => {
  return (
    <>
      <div className={style.sectionWrapper}>
        <div className={style.titleWrapper}>
          <Text component={'p'}>
            Ecology
          </Text>
        </div>

        <div className={style.section}>
          <div className={style.container}>
            <div className={style.imageWrapper}>
              <Image fit={'cover'} src={ImageOne} width={'100%'} height={'100%'} />
              <div className={style.textWrapper}>
                <Text component={'p'}>
                  CONTROL AND COMPLIANCE MONITORING
                </Text>
                <Text component={'span'}>
                  When it comes to the composition of raw gases, emissions, and ambient air, many factors and values
                  must be monitored and analyzed, from industrial production processes to fundamental research. Our
                  high-precision measurement and analysis instruments assist you in your usage for environmental
                  protection and occupational safety, limit value compliance, and process flow optimization.
                </Text>
              </div>
            </div>

            <div className={style.line}>
              <hr />
              <Text component={'span'}> / / </Text>
              <hr />
            </div>
            <div className={style.cards}>

              <div className={style.card}>
                <Image fit={'cover'} height={'238px'} width={'100%'} src={ImageTwo} alt={'ImageOne'} />
                <Text component={'p'}>
                  MONITORING
                </Text>
                <Text component={'span'} className={style.text}>
                  Comprehensive monitoring of industrial production processes guarantees that plant operators may not
                  only respond to abnormalities in the process flow in a timely manner but also actively optimize the
                  process. Time-delayed data capture, such as through discontinuous measurements, is frequently
                  insufficient for this purpose. Data must be gathered and processed online as soon as it is
                  accessible—in real-time.
                </Text>
                <Button className={style.btn}>
                  READ MORE
                </Button>
              </div>
              <div className={style.card}>
                <Image fit={'cover'} height={'238px'} width={'100%'} src={ImageThree} alt={'ImageOne'} />
                <Text component={'p'}>
                  EMISSION
                </Text>
                <Text component={'span'} className={style.text}>
                  The primary sources of pollution generated by emissions are industry and transportation. Monitoring
                  and adherence to limit values help to safeguard our environment—a societal obligation made obvious by
                  the constant and continuing tightening of environmental and safety criteria. We have committed to
                  meeting this obligation by developing future-oriented solutions in emission measuring technology and
                  raw gas monitoring.
                </Text>
                <Button className={style.btn}>
                  READ MORE
                </Button>
              </div>
              <div className={style.card}>
                <Image fit={'cover'} height={'238px'} width={'100%'} src={ImageTwo} alt={'ImageOne'} />
                <Text component={'p'}>
                  ENVIRONMENT
                </Text>
                <Text component={'span'} className={style.text}>
                  One of the most important factors in ensuring people’s health and well-being in workplaces, homes, and
                  public spaces is air quality. Fine particles such as dust, aerosols, as well as gaseous pollutants,
                  can have a significant influence on air quality. LABPROM IMPORT distributes high-tech equipment and
                  solutions that enable the measurement and comprehension of these particles and gaseous contaminants,
                  allowing appropriate choices to be taken.
                </Text>
                <Button className={style.btn}>
                  READ MORE
                </Button>
              </div>

            </div>
          </div>
        </div>
      </div>
    </>
  );
};